### ISSUE TITLE
Add results for D app compiled with LDC

### ISSUE THREAD

**Issue by buggins** [nuald/simple-web-benchmark#4]
DMD is a reference D compiler which provides only basic optimizations.
For better results it's possible to use LLVM based LDC compiler.
Please add D / LDC testing results to table.

Installation / downloads: [LDC installation](https://github.com/ldc-developers/ldc#installation)

Compiling & running:

         dub run --compiler=ldc2 --build=release

If ldc2 executable is not in path, use fully qualified path name.

**Comment by buggins** [comment]
UPD: I don't see any performance changes when test is built by ldc under windows.
But selection of libevent configuration speeds up it twice.

dub.json

    {
        "name": "vibedtest",
        "targetName": "vibedtest",
        "targetType": "executable",
        "targetPath": "bin",
        "dependencies": {
            "vibe-d": "~>0.8.1"
        },
        "subConfigurations": {
            "vibe-d": "libevent"
        },
        "versions": [
            "VibeDefaultMain", "VibeManualMemoryManagement"
        ]
    }

**Comment by nuald** [comment]
Looks like macOS still has the performance issues, however I won't trust the averages anyway, and we can reiterate that later after I add the correct metrics and test on other platforms.
